= PGP Email Encryption
:hp-tags: Encrypt and Decrypt emails using OpenPGP

When we send an e-mail from our gmail or any other mail server, in most cases it will be sent over https that means the communication between mail server and mail client or web browser is encrypted via SSL. But at the server end the mails are stored in the plain text, so anyone who has the access to these server  or 3rd party like NSA can monitor the mails continously and can read your mail. That's why it is important to encrypt your mails to ensure that the mail will be unfolded by the addressee itself or to protect from prying eyes, no matter whatever server you are using.  

Email encryption is important when we talk about the Government organizations and Companies sharing their confidential data.


PGP( Pretty Good Privacy ) is a popular method/program used to encrypt and decrypt email over the Internet, as well as authenticate the message with digital signatures and store the encrypted files.

PGP is useful for two things:

1.  Privacy and Security.

2. Authenticity.

By privacy, I mean that you can prevent people from seeing your emails. For example, you can encrypt an email to someone, or encrypt a file with a list of passwords.

By Authenticity, I mean that you can ensure email was sent/written by the person 
you think it was, and that it wasn't modified by a third party. 
These two can be combined.

In this blog I am going to explain, how to encrypt or decrypt your emConfigure PGP in Chrome:ail on *Chrome*.

===== Requirements:
	
    1> Chrome Browser.    
	2> Internet Connection.

===== Configure PGP in Chrome:

We can encrypt and decrypt emails in Chrome using Mymail-Crypt. Mymail-Crypt make OpenPGP encryption available and used by anyone.

	1> Goto the chrome menu Settings ->Extensions -> Get More Extensions or goto the chrome Webstore, Search for Mymail-Crypt, which popup Mymail-crypt window, Click on the “Add to Chrome”.  
    
or you can simply add from this link:https://chrome.google.com/webstore/detail/mymail-crypt-for-gmail/jcaobjhdnlpmopmjhijplpjhlplfkhba?hl=en-US[link]